name = "phoenix-api"
main = "src/app.ts"
compatibility_date = "2023-09-18"



vars = []


r2_buckets = [
  { binding = "r2", bucket_name = "phoenix-dev" }
]

[placement]
mode = "smart"



[env.production]

r2_buckets = [
  { binding = "r2", bucket_name = "phoenix" }
]
