name: deploy

# You need to setup the following secrets:
# CLOUDFLARE_ACCOUNT_ID: Your Cloudflare account ID
# CLOUDFLARE_API_TOKEN: Your API Token generated

# on: workflow_dispatch

# In a real-world scenario you may want to trigger the workflow when pushing on your production branch
on:
  push:
    branches:
      - main

jobs:

  phoenix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          make install_ci

      - name: Run Tests
        run: |
          make test

      - name: Deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          make deploy
